name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wasm4
        run: npm install -g wasm4
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0-dev.2276+3fde14035
      - run: zig version
      - run: zig build -Drelease-small=true
      # zig-out/lib/cart.wasm
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0-dev.2276+3fde14035
      - run: zig fmt --check src/*.zig

